### ISSUE TITLE
KeyCommands via PreferenceKey

### ISSUE THREAD

**Issue by asiliuk** [emcro/SwiftUI-Keyboard-Demo#1]
Hey! Really cool idea and implementation!

I wanted to ask if you considered implementing this via [Preference](https://developer.apple.com/documentation/swiftui/preferencekey) mechanism? It looks like a really good fit for this, because it can combine all KeyCommands that are defined on each view and handle them in global scope

I've played with that idea and your project and it is possible to do.
1. You can create wrapper around UIHostingController
2. Collect all KeyCommands with `.onPreferenceChange` on `ContentView`
3. Handle all calls to commands action in that Wrapper controller

And after that you can use helper method on Views inplace like this
```swift
// in ContentView
.keyCommands(
    KeyCommand(title: "First View", input: "1", modifierFlags: .command) { self.selection = 1 },
    KeyCommand(title: "Second View", input: "2", modifierFlags: .command) { self.selection = 2 }
)
```

if you interested I can open PR with implementation :)

**Comment by emcro** [comment]
Hiya, that sounds like a great idea — please do a PR, would love to check it out as I could see that solution being really useful. Thanks!
